sudo: required
services:
  - docker

before_install:
  - docker build -t nickahermann/frontend -f Dockerfile.dev .

script:
  - docker run nickahermann/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-401424348116"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_ACCESS_KEY"
